name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: npx typedoc --options typedoc.json

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check out the gh-pages-docs branch, create if it doesn't exist already
          if git show-ref --quiet refs/heads/gh-pages-docs; then
            git checkout gh-pages-docs
          else
            git checkout --orphan gh-pages-docs
          fi

          # Remove all existing files in the gh-pages-docs branch
          git rm -rf .

          # Copy the generated docs to the root
          cp -r docs/* .

          # Add all files to git
          git add .

          # Commit the changes
          git commit -m "Deploy updated documentation"

          # Force push to the gh-pages-docs branch
          git push https://x-access-token:${{ secrets.PAGES_TOKEN }}@github.com/${{ github.repository }} gh-pages-docs --force
