name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "typedoc.json"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run typedoc to generate documentation
        run: npx typedoc --options typedoc.json

      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard

      - name: Copy new documentation
        run: cp -R docs/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin gh-pages --force

      - name: Configure GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
