name: Publish to npm and deploy documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate comparison

      - name: Check for changes in src/ folder
        id: check_changes
        run: |
          git fetch origin main
          if git diff --name-only origin/main HEAD^ | grep '^src/'; then
            echo "Changes found in src/ folder"
            echo "check_changes=true" >> $GITHUB_ENV
          else
            echo "No changes in src/ folder"
            echo "check_changes=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Run Tests
        run: |
          npm install
          npm run test
          git reset --hard

      - name: Get previous version
        id: prev-version
        run: |
          git checkout HEAD^
          PREV_VERSION=$(jq -r '.version' package.json)
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV
          echo "Previous version: v$PREV_VERSION"
          git checkout -

      - name: Get current version
        id: curr-version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Current version: v$CURRENT_VERSION"

      - name: Compare versions and bump if necessary
        id: bump_version
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git
          echo "Current Version: $CURRENT_VERSION"
          echo "Previous Version: $PREV_VERSION"

          # Check if the version was manually changed
          if [ "$CURRENT_VERSION" != "$PREV_VERSION" ]; then
            echo "Version manually updated to $CURRENT_VERSION"
          else
            echo "Version not manually updated, bumping patch version"
            npm version patch -m "Update to version %s (workflow)"
            CURRENT_VERSION=$(jq -r '.version' package.json)
            echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
            git push https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git main --follow-tags
          fi
          echo "Version comparison and bump completed"

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Check if tag exists and add if necessary
        run: |
          git fetch --tags
          TAG_VERSION="v${{ env.CURRENT_VERSION }}"
          if git tag -l | grep -q "^$TAG_VERSION$"; then
            echo "Tag $TAG_VERSION already exists"
          else
            git tag -a "$TAG_VERSION" -m "Release $TAG_VERSION"
            git push https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git "$TAG_VERSION"
            echo "Tag $TAG_VERSION added and pushed"
          fi

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public

      - name: Copy docs content to environment
        run: |
          npm run docs
          mkdir -p /tmp/docs
          cp -r docs/* /tmp/docs

      - name: Deploy documentation to gh-pages-docs branch
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout gh-pages-docs || git checkout --orphan gh-pages-docs
          git rm -rf .
          cp -r /tmp/docs/* .
          git add .
          git commit -m "Update Documentation to v${{ env.CURRENT_VERSION }}"
          git push https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git gh-pages-docs --force
